sudo: false
cache: bundler
language: ruby
rvm: 2.4
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec jekyll build -d _site/grainger
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
branches:
  except:
  - gh-pages
